/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotbank

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

class AppTest: StringSpec({
    "should work" {
        val app = App()
        app.hello() shouldBe "hello"
    }

})
