/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotbank

class App {
    fun hello(): String {
       return "hello"
    }
}

fun main() {
    println(App().hello())
}
